Fix 'Session' object has no attribute 'pid' error when spawning apps (#21)
When using the -f flag to spawn an app, the code attempted to access
self.session.pid which doesn't exist on Frida Session objects. The PID
is returned from device.spawn() and needs to be stored separately.

This fix:
- Adds spawned_pid attribute to store the PID when spawning
- Stores the PID returned from device.spawn() in spawned_pid
- Uses spawned_pid instead of session.pid when resuming the process

Fixes the error: AttributeError: 'Session' object has no attribute 'pid'